baseURL = "https://trialtester98.github.io/testing-website/"
languageCode = "en-us"
title = "Jamstack.club"
theme = "jamstackthemes"
paginate = 18
summaryLength = 10
relativeURLs=false
# enableGitInfo = false

rssLimit = 50

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  segment_id = ""
  description = "Free and open-source themes for"
  stackbit_button = false
  iframe_demo = false
  assets_url = "https://assets.jamstackthemes.dev"
  [theme_card]
    show_archetype_icons = false
    show_services_icons = false

[taxonomies]
  archetype = "archetype"

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]
  page = ["HTML"]
